# Generated by Django 3.0.1 on 2020-01-26 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institucional', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Fotos',
            new_name='Foto',
        ),
    ]
