# Generated by Django 3.0.1 on 2020-01-26 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institucional', '0002_auto_20200126_0344'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='slide')),
            ],
        ),
        migrations.RenameField(
            model_name='foto',
            old_name='usuario',
            new_name='trabalho',
        ),
        migrations.AlterField(
            model_name='foto',
            name='foto',
            field=models.ImageField(upload_to='trabalhos'),
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=200)),
                ('trabalho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institucional.Trabalho')),
            ],
        ),
    ]
