# Generated by Django 3.0.1 on 2020-02-02 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institucional', '0003_auto_20200126_0404'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='desc',
            field=models.CharField(default='Sem Descrição', max_length=200),
        ),
    ]
