# Generated by Django 3.0.1 on 2020-02-02 04:23

from django.db import migrations, models
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('institucional', '0006_slide_cropping'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slide',
            name='imagem',
        ),
        migrations.AddField(
            model_name='slide',
            name='image',
            field=models.ImageField(blank=True, upload_to='slide'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('image', '1200x600', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping'),
        ),
    ]
