# Generated by Django 3.0.1 on 2020-02-02 05:28

from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('institucional', '0010_auto_20200202_0213'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyModel',
        ),
        migrations.AlterField(
            model_name='slide',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('imagem', '2400x800', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping'),
        ),
    ]
