# Generated by Django 3.0.1 on 2020-02-18 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institucional', '0011_auto_20200202_0228'),
    ]

    operations = [
        migrations.CreateModel(
            name='Depoimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(blank=True, upload_to='clientes')),
                ('texto', models.TextField()),
            ],
        ),
    ]
