# Generated by Django 3.0.1 on 2020-02-18 00:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institucional', '0012_depoimento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('usuario', models.CharField(max_length=50)),
                ('senha', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='depoimento',
            name='autor',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='institucional.Cliente'),
            preserve_default=False,
        ),
    ]
