# Generated by Django 3.0.1 on 2020-02-22 01:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('institucional', '0014_auto_20200221_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='depoimento',
            name='data',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
