# Generated by Django 3.0.1 on 2020-02-25 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institucional', '0018_auto_20200225_1846'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='usuario',
        ),
    ]
