# Generated by Django 3.0.1 on 2020-02-25 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institucional', '0019_remove_cliente_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='nome',
            field=models.CharField(default='a', max_length=200),
        ),
        migrations.AddField(
            model_name='cliente',
            name='senha',
            field=models.CharField(default='a', max_length=50),
        ),
        migrations.AddField(
            model_name='cliente',
            name='usuario',
            field=models.CharField(default='a', max_length=50),
        ),
    ]
