# Generated by Django 3.0.1 on 2020-02-28 01:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institucional', '0021_auto_20200225_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabalho',
            name='Cliente',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='institucional.Cliente'),
        ),
    ]
