# Generated by Django 3.0.1 on 2020-02-28 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institucional', '0023_auto_20200227_2203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trabalho',
            name='Cliente',
        ),
    ]
