# Generated by Django 3.0.1 on 2020-02-28 01:07

from django.db import migrations, models
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('institucional', '0025_trabalho_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foto',
            name='foto',
        ),
        migrations.AddField(
            model_name='foto',
            name='foto_horizontal',
            field=models.ImageField(blank=True, upload_to='trabalhos'),
        ),
        migrations.AddField(
            model_name='foto',
            name='foto_vertical',
            field=models.ImageField(blank=True, upload_to='trabalhos'),
        ),
        migrations.AlterField(
            model_name='foto',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('foto_vertical', '600x1200', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping'),
        ),
    ]
