# Generated by Django 3.0.1 on 2020-02-28 01:10

from django.db import migrations, models
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('institucional', '0026_auto_20200227_2207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foto',
            name='cropping',
        ),
        migrations.AddField(
            model_name='foto',
            name='croppingh',
            field=image_cropping.fields.ImageRatioField('foto_vertical', '600x1200', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='croppingh'),
        ),
        migrations.AddField(
            model_name='foto',
            name='croppingv',
            field=image_cropping.fields.ImageRatioField('foto_horizontal', '1200x600', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='croppingv'),
        ),
        migrations.AlterField(
            model_name='trabalho',
            name='imagem_capa',
            field=models.ImageField(blank=True, default='sem_foto.png', upload_to='usuarios'),
        ),
    ]
