# Generated by Django 3.0.1 on 2020-02-28 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institucional', '0028_auto_20200227_2212'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trabalho',
            old_name='Cliente',
            new_name='cliente',
        ),
    ]
